/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : Process.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Datasheet   :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2013-Aug 5, 2013, 8:54:36 PM, # CodeGen: 1
 **     Author      : Dong
 **     Abstract    :
 **         This file contains functions for kinds of data processing.
 **     Settings    :
 **
 **     Contents    :
 **                 MainLoop    - void MainLoop(void)
 **
 **     Mail        : pzdongdong@163.com
 **
 **     Revision    : No.  Name        Data/Time        Content
 ** ###################################################################*/
/*!
 * @file Process.h
 * @version 01.00
 * @brief
 *      This file contains functions for kinds of data processing.
 */
/*!
 *  @addtogroup Proc Process module documentation
 *      This module contains functions for kinds of data processing.
 *  @{
 */

/* Module Process */

/* {Default RTOS Adapter} No RTOS includes */
#include "PE_Error.h"
#include "PE_Types.h"

#include "MyHeaders.h"
#include "string.h"

static void Process(EADCFlag);
//static void TransmitMCUData(void);
static LDD_TError SplitRawData(TADCDataPtr adcDataPtr);
static void CopyADCDataToMCUData(EADCFlag adcFlag);
static void PackData(EADCFlag adcFlag);
//static void SwapARMDataBuffer(void);
static void ReadADCData(void);

/*
 * ===================================================================
 * Global Variables
 * ===================================================================
 */
static int chDataCnt[USING_ADC_COUNT] = {0};
static uint8 overflowCnt = 0;

/*
 * ===================================================================
 *     Method      :  MainLoop ()
 */
/*!
 *     @brief
            This methods starts main loop, ADC's conversion and so on.
 *     @param
 *          void
 *     @return
 *          void
 */
/* ===================================================================*/
void MainLoop(void)
{
    extern TMCUPtr tMCUPtr;
    extern volatile bool isStart;

    tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = TRUE;
    tMCUPtr->mcuStatus.isSPI0TxDMATransCompleted = TRUE;
    tMCUPtr->mcuStatus.isSPI1RxDMATransCompleted = TRUE;
    tMCUPtr->mcuStatus.isSPI1TxDMATransCompleted = TRUE;

//    SPI0_BR = (SPI_BR_SPPR(0x02) | SPI_BR_SPR(0x02));   /* Set baud rage register, 1M */
    SPI0_BR = (SPI_BR_SPPR(0x01) | SPI_BR_SPR(0x00)); /* Set baud rate register,6M */
//    SPI0_BR = (SPI_BR_SPPR(0x00) | SPI_BR_SPR(0x00)); /* Set baud rate register,12M */

    /* Enable PortA's interrupt. */
    EIntADNotReady0Enable(EINT_AD_NOT_DRDY0);
//    EIntADNotReady1Enable(EINT_AD_NOT_DRDY1);
    EIntSyncInterruptEnable(EINT_SYNC_INT);
    NVIC_ISER |= NVIC_ISER_SETENA(0x40000000);      /* Enable PortA's hardware interrupt */

//    StartTaskTimer();

    //ADCStartConvertByCommand(eADC0);
    //ADCStartConvertByCommand(eADC1);
    /* Start ADC's conversion at the same time by Pull the start pin high. */
//    GPIOB_PDOR |= 0x06U;    /* B1, B2 */

    while(!isStart);

    for(;;)
    {
//        SwapARMDataBuffer();    /* Swap the data buffer if needed. */

        /* If data of ADC is ready, read it. */
        ReadADCData();

        /* Processing the Data. */
        Process(eADC0);
        Process(eADC1);

        /*  If the ARM requires data, transmit. */
        //TransmitMCUData();
    }
}

/*
 * ===================================================================
 *     Method      : ReadADCData(Module Process)
 */
/*!
 *     @brief
 *          This method reads ADC's data when ADC's is ready to be read.
 *          This method is called in function
 *          EINT_AD_NOT_DRDY0_OnInterrupt or EINT_AD_NOT_DRDY0_OnInterrupt,
 *          file Events.c
 *     @param
 *          adcFlag         - Show which ADC's data is processed.
 *     @return
 *          void
 */
/* ===================================================================*/
static void ReadADCData(void)
{
    extern TADCPtr tADCPtr[USING_ADC_COUNT];
    //EADCFlag adcFlag;

    if(tADCPtr[eADC0]->adcStatus.isDataReady)// && tADCPtr[eADC1]->adcStatus.isDataReady)
    {
        EnableADCSPI(eADC0);
        ADCReadContinuousData(tADCPtr[eADC0]->adcData.rawData, RAW_DATA_SIZE);
        tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
//        tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
//        tMCUPtr->mcuStatus.isSPI0TxDMATransCompleted = FALSE;
        tADCPtr[eADC0]->adcStatus.adcDataStatus = eReceiving;
        tADCPtr[eADC0]->adcStatus.transmitionContent = eData;

//        while(!tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted);
        DisableADCSPI(eADC0);

        tMCUPtr->mcuStatus.isReceivingADCData = FALSE;
        tADCPtr[eADC0]->adcStatus.isDataReady = FALSE;
        tADCPtr[eADC0]->adcStatus.adcDataStatus = eReceived;
        tADCPtr[eADC0]->adcStatus.transmitionContent = eNothing;

        //Process(eADC0);

        EnableADCSPI(eADC1);
        ADCReadContinuousData(tADCPtr[eADC1]->adcData.rawData, RAW_DATA_SIZE);
        tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
//        tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
//        tMCUPtr->mcuStatus.isSPI0TxDMATransCompleted = FALSE;
        tADCPtr[eADC1]->adcStatus.adcDataStatus = eReceiving;
        tADCPtr[eADC1]->adcStatus.transmitionContent = eData;

//        while(!tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted);
        DisableADCSPI(eADC1);

        tMCUPtr->mcuStatus.isReceivingADCData = FALSE;
        tADCPtr[eADC1]->adcStatus.isDataReady = FALSE;
        tADCPtr[eADC1]->adcStatus.adcDataStatus = eReceived;
        tADCPtr[eADC1]->adcStatus.transmitionContent = eNothing;

        //Process(eADC1);
    }

//    while(tADCPtr[eADC0]->adcStatus.isDataReady || tADCPtr[eADC1]->adcStatus.isDataReady)
//    {
//        adcFlag = (TRUE == tADCPtr[eADC0]->adcStatus.isDataReady) ? eADC0 : eADC1;
//        EnableADCSPI(adcFlag);
//        ADCReadContinuousData(tADCPtr[adcFlag]->adcData.rawData, RAW_DATA_SIZE);
//        tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
//        tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
//        tMCUPtr->mcuStatus.isSPI0TxDMATransCompleted = FALSE;
//        tADCPtr[adcFlag]->adcStatus.adcDataStatus = eReceiving;
//        tADCPtr[adcFlag]->adcStatus.transmitionContent = eData;
//
//        while(!tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted);
//        DisableADCSPI(adcFlag);
//
//        tMCUPtr->mcuStatus.isReceivingADCData = FALSE;
//        tADCPtr[adcFlag]->adcStatus.isDataReady = FALSE;
//        tADCPtr[adcFlag]->adcStatus.adcDataStatus = eReceived;
//        tADCPtr[adcFlag]->adcStatus.transmitionContent = eNothing;
//
//        Process(adcFlag);
//    }
}
//void ReadADCData(EADCFlag adcFlag)
//{
//    extern TADCPtr tADCPtr[USING_ADC_COUNT];
//    extern TMCUPtr tMCUPtr;
////    EADCFlag _adcFlag;
////////////////////////////////////////////////////////////////////////////////////////////
//    if(!tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted)
//    {
//        SysTickWriteReloadValueReg(0x3B);
//        SysTickEnable();
//        return;
//    }
//    if(!tMCUPtr->mcuStatus.isReceivingADCData && eIdle == tADCPtr[adcFlag]->adcStatus.adcDataStatus)
//    {
//        EnableADCSPI(adcFlag);
//        ADCReadContinuousData(tADCPtr[adcFlag]->adcData.rawData, RAW_DATA_SIZE);
//        tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
//        tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
//        tADCPtr[adcFlag]->adcStatus.adcDataStatus = eReceiving;
//        tADCPtr[adcFlag]->adcStatus.transmitionContent = eData;
//    }
////////////////////////////////////////////////////////////////////////////////////////////
////    if(tADCPtr[adcFlag]->adcStatus.isDataReady)
////    {
////        if(!tMCUPtr->mcuStatus.isReceivingADCData && tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted)
////        {
////            if(eIdle == tADCPtr[adcFlag]->adcStatus.adcDataStatus)
////            {
////                EnableADCSPI(adcFlag);
////                ADCReadContinuousData(tADCPtr[adcFlag]->adcData.rawData, RAW_DATA_SIZE);
////                tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
////                tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
////                tADCPtr[adcFlag]->adcStatus.adcDataStatus = eReceiving;
////                tADCPtr[adcFlag]->adcStatus.transmitionContent = eData;
////            }
////        }
////        if(tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted)
////        {
////            DisableADCSPI(adcFlag);
////            tADCPtr[adcFlag]->adcStatus.isDataReady = FALSE;
////            tMCUPtr->mcuStatus.isReceivingADCData = FALSE;
////            tADCPtr[adcFlag]->adcStatus.adcDataStatus = eReceived;
////        }
////      }
////////////////////////////////////////////////////////////////////////////////////////////
////    if(tADCPtr[eADC0]->adcStatus.isDataReady || tADCPtr[eADC1]->adcStatus.isDataReady)
////    {
////        _adcFlag = (TRUE == tADCPtr[eADC0]->adcStatus.isDataReady) ? eADC0 : eADC1;
////        if(!tMCUPtr->mcuStatus.isReceivingADCData && tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted)
////        {
////            if(eIdle == tADCPtr[_adcFlag]->adcStatus.adcDataStatus)
////            {
////                EnableADCSPI(_adcFlag);
////                ADCReadContinuousData(tADCPtr[_adcFlag]->adcData.rawData, RAW_DATA_SIZE);
////                tMCUPtr->mcuStatus.isReceivingADCData = TRUE;
////                tMCUPtr->mcuStatus.isSPI0RxDMATransCompleted = FALSE;
////                tADCPtr[_adcFlag]->adcStatus.adcDataStatus = eReceiving;
////                tADCPtr[_adcFlag]->adcStatus.transmitionContent = eData;
////                tADCPtr[_adcFlag]->adcStatus.isDataReady = FALSE;
////            }
////        }
////    }
////////////////////////////////////////////////////////////////////////////////////////////
//}

/*
 * ===================================================================
 *     Method      : Process(Module Process)
 */
/*!
 *     @brief
 *         	The primary routine of processing the data.
 *     @param[in]
 *          adcFlag         - Show which ADC's data is processed.
 *     @return
 *          void
 */
/* ===================================================================*/
static void Process(EADCFlag adcFlag)
{
    extern TADCPtr tADCPtr[USING_ADC_COUNT];

    if(eReceived == tADCPtr[adcFlag]->adcStatus.adcDataStatus)
    {
        SplitRawData(&(tADCPtr[adcFlag]->adcData));
        tADCPtr[adcFlag]->adcStatus.adcDataStatus = eIdle;

        CopyADCDataToMCUData(adcFlag);

        PackData(adcFlag);
    }
}

/*
 * ===================================================================
 *     Method      : TransmitADCData(Module Process)
 */
/*!
 *     @brief
 *          This method transmit MCU's data to ARM when is required.
 *     @param
 *          void
 *     @return
 *          void
 */
/* ===================================================================*/
void TransmitMCUData(void)
{
    extern TMCUPtr tMCUPtr;
    extern TARMPtr tARMPtr;

    if(tARMPtr->armStatus.isRequiringData &&
            //tARMPtr->armStatus.isUploadReady &&
                tMCUPtr->mcuStatus.isSPI1TxDMATransCompleted)
    {
        tARMPtr->armStatus.isRequiringData = FALSE;
        tMCUPtr->mcuStatus.isSPI1TxDMATransCompleted = FALSE;
        IOUploadReadyClrVal();
        SPI1SendData((LDD_DMA_TAddress)tARMPtr->foreBuffer, DATA_FRAME_LENGTH + 1);
        //tARMPtr->armStatus.isTransmittingData = TRUE;
        tARMPtr->armStatus.transmitionContent = eData;
//        tARMPtr->armStatus.isForeBufferEmpty = FALSE;
//        tARMPtr->armStatus.isForeBufferFull = FALSE;
        tARMPtr->armStatus.foreBufferStatus = eRead;
        tARMPtr->armStatus.isUploadReady = FALSE;
    }
}

/*
 * ===================================================================
 *     Method      : SplitRawData(Module Process)
 */
/*!
 *     @brief
 *         	This method splits the ADC raw data to each part of the ADC data
 *         	structure.
 *     @param[in]
 *         	adcDataPtr      - Pointer to ADC data structure.
 *     @return
 *         	                - ERR_PARAM_DATA: The head byte of the raw is not valid,
 *         	                                  so the data is invalid.
 *         	                - ERR_OK: Succeeded to split.
 */
/* ===================================================================*/
static LDD_TError SplitRawData(TADCDataPtr adcDataPtr)
{
    LDD_TError err;
    byte head;
    byte loffStatP;
    byte loffStatN;
    byte regGPIOData;
    int16 channelData;

    head = ((adcDataPtr->rawData[0] & 0xF0) >> 4) & 0x0F;       /* Split head byte from raw data. */
    if(head != RAW_DATA_HEAD)                                   /* If the head byte is not right(0x0C), return with error. */
    {
        err = ERR_PARAM_DATA;
#if DEBUG
        PrintErrorMessage(err);
        printf("%#x\n", head);
#endif
        return err;
    }

    loffStatP  = ((byte)(adcDataPtr->rawData[0] & 0x0F) << 4) & 0xF0;
    loffStatP |= ((byte)(adcDataPtr->rawData[1] & 0xF0) >> 4) & 0x0F;

    loffStatN  = ((byte)(adcDataPtr->rawData[1] & 0x0F) << 4) & 0xF0;
    loffStatN |= ((byte)(adcDataPtr->rawData[2] & 0xF0) >> 4) & 0x0F;

    regGPIOData =  (byte)adcDataPtr->rawData[2] & 0x0F;

    for(int i = 0; i < USING_CHANNEL_COUNT * BYTE_COUNT_PER_CHANNEL; i += 2)    /* Every channel's data is 2 Bytes. */
    {
        channelData = ((int16)adcDataPtr->rawData[RAW_DATA_HEAD_SIZE + i] << 8) & 0xFF00;
        channelData |= (int16)adcDataPtr->rawData[RAW_DATA_HEAD_SIZE + i + 1] & 0x00FF;
        adcDataPtr->channelData[i / 2] = (int16)channelData;
    }

    adcDataPtr->head = (byte)head;
    adcDataPtr->loffStatP = (byte)loffStatP;
    adcDataPtr->loffStatN = (byte)loffStatN;
    adcDataPtr->regGPIOData = (byte)regGPIOData;

    return ERR_OK;
}

/*
 * ===================================================================
 *     Method      : CopyADCDataToMCUData(Module Process)
 */
/*!
 *     @brief
 *          This method copies ADC data from ADC structure to MCU structure.
 *          The format of data in MCU structure
       @verbatim
       --------------------------------------
       | ADC | (Chn) | 1ms 2ms 3ms ... 99ms |
       --------------------------------------
       |  0  | (Ch1) | [0] [1] [2] ... [99] |
       |  0  | (Ch2) | [0] [1] [2] ... [99] |
       |  0  | (Ch3) | [0] [1] [2] ... [99] |
       |  0  | (Ch4) | [0] [1] [2] ... [99] |
       |  0  | (Ch5) | [0] [1] [2] ... [99] |
       |  0  | (Ch6) | [0] [1] [2] ... [99] |
       |  0  | (Ch7) | [0] [1] [2] ... [99] |
       |  0  | (Ch8) | [0] [1] [2] ... [99] |
       ======================================
       |  1  | (Ch1) | [0] [1] [2] ... [99] |
       |  1  | (Ch2) | [0] [1] [2] ... [99] |
       |  1  | (Ch3) | [0] [1] [2] ... [99] |
       |  1  | (Ch4) | [0] [1] [2] ... [99] |
       |  1  | (Ch5) | [0] [1] [2] ... [99] |
       |  1  | (Ch6) | [0] [1] [2] ... [99] |
       |  1  | (Ch7) | [0] [1] [2] ... [99] |
       |  1  | (Ch8) | [0] [1] [2] ... [99] |
       --------------------------------------
       @endverbatim
 *     @param
 *          adcFlag     - Shows which ADC is selected.
 *     @return
 *          void
 */
/* ===================================================================*/
static void CopyADCDataToMCUData(EADCFlag adcFlag)
{
    extern TMCUPtr tMCUPtr;
//    static uint8 chDataCnt[USING_ADC_COUNT] = {0};

    tMCUPtr->mcuData.channelData[adcFlag][0][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[0];
    tMCUPtr->mcuData.channelData[adcFlag][1][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[1];
    tMCUPtr->mcuData.channelData[adcFlag][2][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[2];
    tMCUPtr->mcuData.channelData[adcFlag][3][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[3];
    tMCUPtr->mcuData.channelData[adcFlag][4][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[4];
    tMCUPtr->mcuData.channelData[adcFlag][5][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[5];
    tMCUPtr->mcuData.channelData[adcFlag][6][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[6];
    tMCUPtr->mcuData.channelData[adcFlag][7][chDataCnt[adcFlag]] = tADCPtr[adcFlag]->adcData.channelData[7];

//    chDataCnt[adcFlag]++;
//    chDataCnt[adcFlag] %= CHANNEL_DATA_COUNT;
}

/*
 * ===================================================================
 *     Method      : PackData (Module Process)
 */
/*!
 *     @brief
 *         	This method is called to pack filtered data adapting to the
 *         	format according to the protocol between MCU and ARM.
 *     @param
 *         	adcFlag         - Show which ADC's is being processed.
 *     @return
 *         	void
 */
/* ===================================================================*/
static void PackData(EADCFlag adcFlag)
{
    extern TMCUPtr tMCUPtr;
    extern TARMPtr tARMPtr;
//    static int chDataCnt[USING_ADC_COUNT] = {0};
    int off;

    if(eFull == tARMPtr->armStatus.backBufferStatus || eOverflow == tARMPtr->armStatus.backBufferStatus)
    {
        tARMPtr->armStatus.backBufferStatus = eOverflow;
        overflowCnt++;
        return;
    }

    for(int channelNum = 0;  channelNum < USING_CHANNEL_COUNT; channelNum++)
    {
        off = 8 /* Head Bits in a pack, eg. 0xB7, MCU No., etc. */
                + USING_CHANNEL_COUNT * CHANNEL_PACKAGE_LENGTH * adcFlag  /* The ADC0's data is in the front of ADC1's data. */
                    + 3 * (channelNum + 1)  /* Every channel's data pack has a head of 3 bits. */
                        + CHANNEL_DATA_COUNT * 2 * channelNum   /* every channel's data is 200 bits apart of the 3-bit head. */
                            + chDataCnt[adcFlag] * 2;   /* every channel's data at on time is 2 bits. */

        tARMPtr->backBuffer[off] = tMCUPtr->mcuData.channelData[adcFlag][channelNum][chDataCnt[adcFlag]] >> 8 & 0xFFU;
        tARMPtr->backBuffer[off + 1] = tMCUPtr->mcuData.channelData[adcFlag][channelNum][chDataCnt[adcFlag]] & 0xFFU;
    }

    chDataCnt[adcFlag]++;
    chDataCnt[adcFlag] %= CHANNEL_DATA_COUNT;
    if(!chDataCnt[0] && !chDataCnt[1])
    {
//        tARMPtr->armStatus.isBackBufferEmpty = FALSE;
//        tARMPtr->armStatus.isBackBufferFull = TRUE;
        tARMPtr->armStatus.backBufferStatus = eFull;
    }
    else
    {
//        tARMPtr->armStatus.isBackBufferEmpty = FALSE;
//        tARMPtr->armStatus.isBackBufferFull = FALSE;
        tARMPtr->armStatus.backBufferStatus = eWrite;
    }
}
//static void PackData(void)
//{
//    extern TMCUPtr tMCUPtr;
//    extern TARMPtr tARMPtr;
//    byte channelPackage[CHANNEL_PACKAGE_LENGTH] = {0};
//
//    channelPackage[0] = CHANNEL_PACKAGE_HEAD_BIT;
//    channelPackage[2] = 0x00U;      /* Channel package state bit */
//
//    for(int adcNum = 0; adcNum < USING_ADC_COUNT; adcNum++)
//    {
//        for(int channelNum = 0; channelNum < USING_CHANNEL_COUNT; channelNum++)
//        {
//            channelPackage[1] = MCU_NUMBER * USING_CHANNEL_COUNT * USING_ADC_COUNT
//                                    + adcNum * USING_CHANNEL_COUNT
//                                        + channelNum;      /* Channel number */
//
//            for(int dataNum = 3; dataNum < CHANNEL_PACKAGE_LENGTH; dataNum += 2)
//            {
//                channelPackage[dataNum] = tMCUPtr->mcuData.channelData[adcNum][channelNum][dataNum] >> 8 & 0xFFU;
//                channelPackage[dataNum + 1] = tMCUPtr->mcuData.channelData[adcNum][channelNum][dataNum] & 0xFFU;
//            }
//
//            int startPos = (int)tARMPtr->armDataLeft.dataFrame + 7
//                               + adcNum * USING_CHANNEL_COUNT * CHANNEL_PACKAGE_LENGTH
//                                   + CHANNEL_PACKAGE_LENGTH;
//            if(eLEFT == tARMPtr->armStatus.eARMDataBufFlag)
//            {
//                memcpy(startPos, channelPackage, CHANNEL_PACKAGE_LENGTH);
//            }
//            else if(eRIGHT == tARMPtr->armStatus.eARMDataBufFlag)
//            {
//                memcpy(startPos, channelPackage, CHANNEL_PACKAGE_LENGTH);
//            }
//        }
//    }
//
//    tMCUPtr->mcuStatus.isUploadReady = TRUE;
//}

/*
 * ===================================================================
 *     Method      : SwapARMDataBuffer (Module Process)
 */
/*!
 *     @brief
 *          This method is called to swap the arm's data. Decide either the
 *          armLeftData or armRightData is the foreground buffer or background
 *          buffer.
 *     @param
 *          void
 *     @return
 *          void
 */
/* ===================================================================*/
void SwapARMDataBuffer(void)
{
    if(eNull == tARMPtr->armStatus.foreBufferStatus && eNull == tARMPtr->armStatus.backBufferStatus)
    {
        tARMPtr->foreBuffer = tARMPtr->armDataRight.dataFrame;
        tARMPtr->backBuffer = tARMPtr->armDataLeft.dataFrame;
//        tARMPtr->armStatus.isForeBufferEmpty = FALSE;
//        tARMPtr->armStatus.isForeBufferFull = FALSE;
//        tARMPtr->armStatus.isBackBufferEmpty = TRUE;
//        tARMPtr->armStatus.isForeBufferFull = FALSE;
        tARMPtr->armStatus.foreBufferStatus = eEmpty;
        tARMPtr->armStatus.backBufferStatus = eEmpty;
        tARMPtr->armStatus.isUploadReady = FALSE;

        tARMPtr->foreBuffer[6] = (tARMPtr->foreBuffer[6] & 0x01)
                               | ((tARMPtr->armStatus.foreBufferStatus << 1) & 0x0EU);
        if(eOverflow == tARMPtr->armStatus.foreBufferStatus)
        {
            tARMPtr->foreBuffer[7] = overflowCnt / 2;
        }
        else if(eWrite == tARMPtr->armStatus.foreBufferStatus)
        {
            tARMPtr->foreBuffer[7] = CHANNEL_DATA_COUNT - chDataCnt[eADC1];
        }
    }
    else
    {
        //tARMPtr->backBuffer[7] = tARMPtr->armStatus.backBufferStatus;

        byte* temp;
        temp = tARMPtr->foreBuffer;
        tARMPtr->foreBuffer = tARMPtr->backBuffer;
        tARMPtr->backBuffer = temp;
        tARMPtr->armStatus.foreBufferStatus = tARMPtr->armStatus.backBufferStatus;
        tARMPtr->armStatus.backBufferStatus = eEmpty;
        tARMPtr->armStatus.isUploadReady = FALSE;

        tARMPtr->foreBuffer[6] = (tARMPtr->foreBuffer[6] & 0x01)
                               | ((tARMPtr->armStatus.foreBufferStatus << 1) & 0x0EU);
        if(eOverflow == tARMPtr->armStatus.foreBufferStatus)
        {
            tARMPtr->foreBuffer[7] = overflowCnt / 2;
        }
        else if(eWrite == tARMPtr->armStatus.foreBufferStatus)
        {
            tARMPtr->foreBuffer[7] = CHANNEL_DATA_COUNT - chDataCnt[eADC1];
        }
    }

    chDataCnt[eADC0] = 0;
    chDataCnt[eADC1] = 0;
    overflowCnt = 0;
}
//static void SwapARMDataBuffer(void)
//{
//    extern TARMPtr tARMPtr;
//
//    //if(!tARMPtr->foreBuffer && !tARMPtr->backBuffer)
//    if(eNull == tARMPtr->armStatus.foreBufferStatus && eNull == tARMPtr->armStatus.backBufferStatus)
//    {
//        tARMPtr->backBuffer = tARMPtr->armDataLeft.dataFrame;
////        tARMPtr->armStatus.isForeBufferEmpty = FALSE;
////        tARMPtr->armStatus.isForeBufferFull = FALSE;
////        tARMPtr->armStatus.isBackBufferEmpty = TRUE;
////        tARMPtr->armStatus.isForeBufferFull = FALSE;
//        tARMPtr->armStatus.foreBufferStatus = eNull;
//        tARMPtr->armStatus.backBufferStatus = eEmpty;
//        tARMPtr->armStatus.isUploadReady = FALSE;
//    }
//    //else if(tARMPtr->armStatus.isForeBufferEmpty && tARMPtr->armStatus.isBackBufferFull)
//    else if(eFull == tARMPtr->armStatus.backBufferStatus)
//    {
//        if(eNull == tARMPtr->armStatus.foreBufferStatus)
//        {
//            tARMPtr->foreBuffer = tARMPtr->backBuffer;
//            tARMPtr->backBuffer = (tARMPtr->backBuffer == tARMPtr->armDataLeft.dataFrame) ? tARMPtr->armDataRight.dataFrame : tARMPtr->armDataLeft.dataFrame;
////            tARMPtr->armStatus.isForeBufferEmpty = FALSE;
////            tARMPtr->armStatus.isForeBufferFull = FALSE;
////            tARMPtr->armStatus.isBackBufferEmpty = TRUE;
////            tARMPtr->armStatus.isForeBufferFull = FALSE;
//            tARMPtr->armStatus.foreBufferStatus = eFull;
//            tARMPtr->armStatus.backBufferStatus = eEmpty;
//            tARMPtr->armStatus.isUploadReady = TRUE;
//        }
//        if(eEmpty == tARMPtr->armStatus.foreBufferStatus)
//        {
//            byte* temp;
//
//            temp = tARMPtr->foreBuffer;
//            tARMPtr->foreBuffer = tARMPtr->backBuffer;
//            tARMPtr->backBuffer = temp;
//
////            tARMPtr->armStatus.isForeBufferEmpty = FALSE;
////            tARMPtr->armStatus.isForeBufferFull = TRUE;
////            tARMPtr->armStatus.isBackBufferEmpty = TRUE;
////            tARMPtr->armStatus.isForeBufferFull = FALSE;
//            tARMPtr->armStatus.foreBufferStatus = eFull;
//            tARMPtr->armStatus.backBufferStatus = eEmpty;
//            tARMPtr->armStatus.isUploadReady = TRUE;
//        }
//    }
//}

    /* End Process */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */


